export default [
    {
        uid: 'L1.100',
        name: '-',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.FAN, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: [Temperature(20), Temperature(24)],
        heatRange: [Temperature(24), Temperature(26)],
        lock: null
    },
    {
        uid: 'L1.101',
        name: '-',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.FAN, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: [Temperature(20), Temperature(24)],
        heatRange: [Temperature(24), Temperature(26)],
        lock: null
    },
    {
        uid: 'L1.102',
        name: '-',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.FAN, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: [Temperature(20), Temperature(24)],
        heatRange: [Temperature(24), Temperature(26)],
        lock: null
    },
    {
        uid: 'L1.103',
        name: '-',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.FAN, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: [Temperature(20), Temperature(24)],
        heatRange: [Temperature(24), Temperature(26)],
        lock: null
    },
    {
        uid: 'L1.104',
        name: '-',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.FAN, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: [Temperature(20), Temperature(24)],
        heatRange: [Temperature(24), Temperature(26)],
        lock: null
    },
    {
        uid: 'L7.000',
        name: 'Guest Unit',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.002',
        name: 'Laundy Room',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.003',
        name: 'Kitchen',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.004',
        name: 'Baby\'s Room',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.005',
        name: 'Guest Room',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.006',
        name: 'Playroom',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.007',
        name: 'Kid\'s Room',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.008',
        name: 'Dining Room',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },   
    {
        uid: 'L7.009',
        name: 'Master',
        visible: true,
        modes: [Mode.COOL, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.010',
        name: 'Living Room',
        visible: true,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
    {
        uid: 'L7.011',
        name: 'Dining Room 2',
        visible: false,
        modes: [Mode.COOL, Mode.DRY, Mode.HEAT, Mode.AUTO],
        speeds: [Speed.LOW, Speed.MEDIUM, Speed.HIGH, Speed.AUTO],
        time: null,
        coolRange: null,
        heatRange: null,
        lock: null
    },
]