export default {
    serialNumber: "050036F6",
    version: "0.9.4 (PCB Rev 5.7)",
    buildDate: new Date("2022-04-04T10:49:33.000Z"),
    application: "Standard",
    usbVCOMPort: 1,
    baudRate: 9600,
    echo: true,
    verbose: false,
    vaMode: 0,
    port: 10102,
    prompt: true,
    degrees: "C",
    melody: "Murka",
    filter: "-",
    hvacLines: 1,
    maxIndoors: 256,
    proSize: 0,
    resetOnAssert: false,
    foreachBreak: "return on error",
    mmiLock: false,
}
